# Generated by Django 2.2.4 on 2019-10-24 06:01

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('nickname', models.TextField()),
                ('age', models.IntegerField(default=25)),
                ('gender', models.CharField(default='M', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('company_name', models.TextField()),
                ('ingredient_list', django.contrib.postgres.fields.jsonb.JSONField()),
                ('heavy_metal', django.contrib.postgres.fields.jsonb.JSONField()),
                ('sungsang', models.TextField()),
                ('intake_hint', models.TextField()),
                ('intake_method', models.TextField()),
                ('preservation', models.TextField()),
                ('image_url', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('product_to_function', models.ManyToManyField(related_name='function_to_product', to='api.Function')),
                ('product_to_ingredient', models.ManyToManyField(related_name='ingredient_to_product', to='api.Ingredient')),
            ],
        ),
    ]
