# Generated by Django 2.2.6 on 2019-10-24 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_sungsang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='distrbution',
        ),
    ]
