# Generated by Django 2.2.6 on 2019-10-24 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_product_distrbution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='heavy_metal',
            new_name='heavy_metal_list',
        ),
    ]
